
source = ./hyprland/colors.conf
source = ./hyprland/look-and-feel.conf
source = ./hyprland/env.conf
source = ./hyprland/monitors.conf

windowrule = float,class:gtkgreet

$wallpaper = sh -c "/etc/greetd/scripts/load_wallpaper.sh"
exec-once = hyprpaper
exec-once = $wallpaper
exec-once = hypridle -c "/etc/greetd/hypridle.conf"

exec-once = gtkgreet --command "/etc/greetd/scripts/start-hyprland.sh"; hyprctl dispatch exit
