
source = ./hyprland/colors.conf
source = ./hyprland/look-and-feel.conf
source = ./hyprland/env.conf
source = ./hyprland/monitors.conf

windowrule = match:class gtkgreet, float on
windowrule = match:class gtkgreet, size (monitor_w*0.4) (monitor_h*0.2)
windowrule = match:class gtkgreet, center on

$wallpaper = sh -c "/usr/share/scripts/load_wallpaper.sh"
exec-once = hyprpaper
exec-once = $wallpaper
exec-once = hypridle -c "/etc/greetd/hypridle.conf"

exec-once = gtkgreet --command "start-hyprland > /dev/null"; hyprctl dispatch exit
