[terminal]
vt = 1

[default_session]
# command = "gtkgreet --remember --greeter /usr/share/gtkgreet/greeter"
# command = "/home/otto/.local/share/script/start-hyprland.sh"
command = "Hyprland --config /etc/greetd/hyprland.conf > /dev/null "
user = "otto" 

# [initial_session]
# command = "/home/otto/.local/share/script/start-hyprland.sh"
# user = "otto"
