
source = /etc/greetd/hyprland/colors.conf
source = /etc/greetd/hyprland/look-and-feel.conf
source = /etc/greetd/hyprland/env.conf
source = /etc/greetd/hyprland/monitors.conf

$wallpaper = sh -c "$HOME/.local/share/script/load_wallpaper.sh"
exec-once = hyprpaper
exec-once = $wallpaper

exec-once = gtkgreet --command "/home/otto/.local/share/script/start-hyprland.sh"; hyprctl dispatch exit
