################
### MONITORS ###
################

monitor=,preferred,auto,auto

###################
### MY PROGRAMS ###
###################
source = ./hyprland/autostart.conf
source = ./hyprland/colors.conf
source = ./hyprland/look-and-feel.conf
source = ./hyprland/env.conf
source = ./hyprland/bindings.conf
source = ./hyprland/rules.conf
source = ./hyprland/monitors.conf
