#################
### AUTOSTART ###
#################
exec-once = hyprpaper
exec-once = hypridle
exec-once = sh -c "/usr/share/scripts/load_wallpaper.sh"
exec-once = waybar
exec-once = sh -c "sudo /usr/share/scripts/connect-to-nas.sh"
exec-once = swaync
exec-once = sh -c "kitty --listen-on unix:/tmp/kitty tmux"
exec = xsettingsd
