###################
### MY PROGRAMS ###
###################
# Set programs that you use
$wallpaper = sh -c "/usr/share/scripts/load_wallpaper.sh"
$lockscreen = sh -c "/usr/share/scripts/lockscreen.sh boot"
$nas = sh -c "sudo /usr/share/scripts/connect-to-nas.sh"
$tmux = sh -c "kitty --listen-on unix:/tmp/kitty tmux"

#################
### AUTOSTART ###
#################
exec-once = hyprpaper
exec-once = hypridle
exec-once = $lockscreen
exec-once = $wallpaper
exec-once = waybar
exec-once = $nas
exec-once = swaync
exec-once = $tmux

exec = xsettingsd
exec = systemctl --user start gcr-ssh-agent.socket
