windowrule = match:class blender, opacity 1
windowrule = match:class waybar, no_focus on
windowrule = match:class wofi, float on
windowrule = match:class wofi, stay_focused on
windowrule = match:class wofi, no_anim on
windowrule = match:class wofi, dim_around on
windowrule = match:class wofi, pseudo on
windowrule = match:class Squeak, fullscreen on
windowrule = match:class kitty, workspace 1
windowrule = match:class brave-browser, workspace 2
windowrule = match:class blender, workspace 3
windowrule = match:class unity-editor, workspace 4
windowrule = match:class thunderbird, workspace 5
windowrule = match:class obsidian, workspace 6
windowrule = match:class Postman, workspace 7
windowrule = match:class kitty, fullscreen on

