set -g default-shell "/usr/bin/nu" 
set -g @continuum-restore 'on' # Restore tmux sessions automatically on startup
set -g @resurrect-capture-pane-contents 'on' # Capture pane contents
set -g @resurrect-strategy-nvim 'session' # Restore nvim sessions if applicable
set -g @resurrect-processes 'ssh vim "~nvim" "~nvim -S" "~claude --continue" "~python" "~node"'
set-hook -g after-new-session 'run-shell "sleep 0.1 && tmux display-popup -E -w 100% -h 100% ~/.config/tmux/config/resurect-loading.sh"'
set -g allow-passthrough on
set-option -g focus-events on
set-option -a terminal-features 'xterm-256color:RGB'
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"
unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after dragging with mouse

# Build the format string piece by piece

# Set the option
set-option -g automatic-rename-format '#{?pane_in_mode, tmux,#{?#{==:#{pane_current_command},nvim}, ,}#{?#{==:#{pane_current_command},claude},󰚩 ,}#{?#{==:#{pane_current_command},nu}, ,}#{?#{==:#{pane_current_command},git},󰊢 ,}#{?#{==:#{pane_current_command},lazygit},󰊢 ,}#{?#{==:#{pane_current_command},cargo}, ,}#{?#{==:#{pane_current_command},python},󰌠 ,}#{?#{==:#{pane_current_command},node}, ,}#{?#{==:#{pane_current_command},ssh},󰣀 ,}#{?#{==:#{pane_current_command},htop}, ,}#{?#{==:#{pane_current_command},docker},,}#{pane_current_command}}#{?pane_dead,[dead],}'
