set -g default-shell "/usr/bin/nu" 
set -g @continuum-restore 'on' # Restore tmux sessions automatically on startup
set -g @resurrect-capture-pane-contents 'on' # Capture pane contents
set -g @resurrect-strategy-nvim 'session' # Restore nvim sessions if applicable
set -g @resurrect-processes 'ssh vim "~nvim" "~claude --continue" "~python" "~node"'
set-hook -g after-new-session 'run-shell "sleep 0.1 && tmux display-popup -E -w 100% -h 100% ~/.config/tmux/config/resurect-loading.sh"'
set -g allow-passthrough on
set-option -g focus-events on
set-option -a terminal-features 'xterm-256color:RGB'
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"
unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after dragging with mouse

