set -g status-position top 
set -g pane-border-status top 
set -g @rose_pine_variant 'moon'
set -g pane-border-format ''
set -g base-index 1 # Start window numbering at 1 instead of 0
set -g @rose_pine_bar_bg_disable 'on' # Disables background color, for transparent terminal emulators
set -g @rose_pine_bar_bg_disabled_color_option 'default'
set -g @rose_pine_
set -g @rose_pine_field_separator ' | ' # Again, 1-space padding, it updates with prefix + I
set -g @rose_pine_window_separator ' - ' # Replaces the default `:` between the window number and name
set -g @rose_pine_window_status_separator "  " # Changes the default icon that appears between window names
set -g @rose_pine_session_icon ''
set -g @rose_pine_status_right_prepend_section '#{prefix_highlight}'
set -g @rose_pine_show_current_program 'on'
set -g @rose_pine_disable_active_window_menu 'on'
set -g @prefix_highlight_fg '#232136,bold' # default is 'colour231'
set -g @prefix_highlight_bg '#eb6f92'  # default is 'colour04'
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_copy_mode_attr 'fg=#232136,bg=#f6c177,bold' # default is 'fg=default,bg=yellow'
set -g @prefix_highlight_show_sync_mode 'on'
set -g @prefix_highlight_sync_mode_attr 'fg=black,bg=green' # default is 'fg=default,bg=yellow'
set -g @prefix_highlight_prefix_prompt ''
set -g @prefix_highlight_copy_prompt ''
set -g @prefix_highlight_sync_prompt ''
