set -g status-position top 
set -g pane-border-status top 
set -g @rose_pine_variant 'moon'
set -g pane-border-format ''
set -g base-index 1 # Start window numbering at 1 instead of 0
set -g @rose_pine_bar_bg_disable 'on' # Disables background color, for transparent terminal emulators
set -g @rose_pine_bar_bg_disabled_color_option 'default'
set -g @rose_pine_only_windows 'on' # Leaves only the window module, for max focus and space
# set -g @rose_pine_show_current_program 'off' # Forces tmux to show the current running program as window name
# set -g @rose_pine_show_pane_directory 'off' # Forces tmux to show the current directory as window name
# Previously set -g @rose_pine_window_tabs_enabled

# # Example values for these can be:
# set -g @rose_pine_left_separator ' > ' # The strings to use as separators are 1-space padded
# set -g @rose_pine_right_separator ' ' # Accepts both normal chars & nerdfont icons
# set -g @rose_pine_field_separator ' | ' # Again, 1-space padding, it updates with prefix + I
# set -g @rose_pine_window_separator ' - ' # Replaces the default `:` between the window number and name
#
# # These are not padded
# set -g @rose_pine_session_icon '' # Changes the default icon to the left of the session name
# set -g @rose_pine_current_window_icon '' # Changes the default icon to the left of the active window name
# set -g @rose_pine_folder_icon '' # Changes the default icon to the left of the current directory folder
# set -g @rose_pine_username_icon '' # Changes the default icon to the right of the hostname
# set -g @rose_pine_hostname_icon '󰒋' # Changes the default icon to the right of the hostname
# set -g @rose_pine_date_time_icon '󰃰' # Changes the default icon to the right of the date module
set -g @rose_pine_window_status_separator "  " # Changes the default icon that appears between window names
# set -g @rose_pine_window_status_separator " ┃ " # Changes the default icon that appears between window names
# set -g @rose_pine_window_status_separator " ┃ " # Changes the default icon that appears between window names

# Very beta and specific opt-in settings, tested on v3.2a, look at issue #10
# set -g @rose_pine_prioritize_windows 'on' # Disables the right side functionality in a certain window count / terminal width
# set -g @rose_pine_width_to_hide '80' # Specify a terminal width to toggle off most of the right side functionality
# set -g @rose_pine_window_count '5'

# Add to the beginning / end of the left and right sections your own.
# set -g @rose_pine_status_left_prepend_section '#{tmux_mode_indicator}'
# set -g @rose_pine_status_left_append_section ''
# set -g @rose_pine_status_right_prepend_section ''
# set -g @rose_pine_status_right_append_section ''
#

